services:
  cloudstorages.server:
    image: cloudstorages.server:dev
    build:
      context: .
      dockerfile: CloudStorages.Server/Dockerfile
    



# docker build -f CloudStorages.Server/Dockerfile -t cloudstorages.server:dev .
      
# docker run -d --name cloudstorages-server -p 8080:80 `
# -e ASPNETCORE_ENVIRONMENT=Development `
# -e ASPNETCORE_URLS="http://+:80" `
# cloudstorages.server:dev


